workspace:
  base: /go/src
  path: github.com/appleboy/gin-lambda

pipeline:
  lint:
    image: golang:1.9.2
    group: testing
    commands:
      - make zip

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ success, failure ]
