workspace:
  base: /go/src
  path: github.com/appleboy/gin-lambda

pipeline:
  build:
    image: golang:1.9.2
    commands:
      - GOOS=linux go build -o main .

  zip:
    image: ubuntu:16.04
    commands:
      - apt-get install -y zip
      - zip deployment.zip main

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ success, failure ]
