workspace:
  base: /go/src
  path: github.com/appleboy/gin-lambda

pipeline:
  build:
    image: golang:1.9.2
    commands:
      - GOOS=linux go build -o main .

  lambda:
    image: appleboy/drone-lambda
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    region: ap-southeast-1
    function_name: gin
    source:
      - main

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ success, failure ]
